### ISSUE TITLE
Feature extraction layer

### ISSUE THREAD

**Issue by zzz135790** [koc-lab/TrainableFrFT#1]
Why is there only a frft pooling layer in the code? Can you provide code related to time series prediction tasks? I would like to use frft as a feature extraction layer. Thank you

**Comment by kocemir** [comment]
It will  be added soon. But until this time,  you can use the standard frft code to transform your input features first, process it in a sequence model that you design, and then convert to time domain by inverse frft.

**Comment by tunakasif** [comment]
> I would like to use frft as a feature extraction layer.

You can refer to the [GitHub page of `torch-frft`](https://github.com/tunakasif/torch-frft), which is the installable Python package. You can use the transform itself or use the examples of custom trainable layers.

**Comment by zzz135790** [comment]
> It will be added soon. But until this time, you can use the standard frft code to transform your input features first, process it in a sequence model that you design, and then convert to time domain by inverse frft.它将很快添加。但在此之前，您可以先使用标准 frft 代码转换输入特征，在您设计的序列模型中对其进行处理，然后通过反向 frft 转换为时域。

Thank you

**Comment by zzz135790** [comment]
> > I would like to use frft as a feature extraction layer.我想使用 frft 作为特征提取层。
> 
> You can refer to the [GitHub page of `torch-frft`](https://github.com/tunakasif/torch-frft), which is the installable Python package. You can use the transform itself or use the examples of custom trainable layers.可以参考 `torch-frft` 的 GitHub 页面，它是可安装的 Python 包。您可以使用转换本身，也可以使用自定义可训练层的示例。

Thank you
